experiment:
  imgsz: 640
  epochs: 10
  batch: 16
  workers: 4
  conf_thres: 0.25
  iou_thres: 0.5
  seed: 42

dataset:
  yaml: datasets/yolo/parkinglot.yaml
  folds: 5
  fold_index: 0

wandb:
  project: ParkingLotOD-YOLOv3
  entity: null
  run_name: null

model:
  name: yolov3
  weights: null
  optimizer: adam     # often used for v3; you can switch to sgd if preferred
  lr0: 0.003
  lrf: 0.04
  weight_decay: 0.00001

augment:
  hsv: true
  flip: true
  scale: true
  affine: true
  cutout: true
  mixup: true

search:
  trials: 25
  timeout_min: null



